name: Build Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Version File
        run: |
          echo ${{ github.sha }} > version.txt
          echo ${{ github.ref }} >> version.txt

      - name: Create Windows Executable
        run: |
          pyinstaller --noconfirm --onefile --windowed --name="Automacao Ozia" automacao_ozia_gui.py --add-data "version.txt;." --collect-all customtkinter

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Automacao-Ozia-Windows
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Version File
        run: |
          echo ${{ github.sha }} > version.txt
          echo ${{ github.ref }} >> version.txt

      - name: Create Linux Executable
        run: |
          pyinstaller --noconfirm --onefile --windowed --name="automacao_ozia" automacao_ozia_gui.py --add-data "version.txt:." --collect-all customtkinter

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Automacao-Ozia-Linux
          path: dist/

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Automacao-Ozia-Windows
          path: windows-dist

      - uses: actions/download-artifact@v2
        with:
          name: Automacao-Ozia-Linux
          path: linux-dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-dist/*
            linux-dist/*
          name: Release ${{ github.sha }}
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
